# Generated by Django 3.0.4 on 2024-03-06 12:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0006_auto_20240302_0053'),
        ('accounts', '0002_auto_20240226_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.TextField(blank=True, max_length=100, null=True)),
                ('title', models.TextField(max_length=100)),
                ('first_author', models.TextField(max_length=100)),
                ('pub_year', models.IntegerField(default=0)),
                ('genre', models.TextField(max_length=100)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('summary', models.TextField(max_length=500)),
                ('report', models.TextField(max_length=5000)),
                ('good_count', models.IntegerField(default=0)),
                ('chat_count', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('edit_count', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_owner', to='accounts.Account')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='PaperChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=140)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('reply_id', models.IntegerField(default=-1)),
                ('reply_count', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paperchat_owner', to='accounts.Account')),
                ('paperrecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.PaperRecord')),
            ],
            options={
                'ordering': ('pub_date',),
            },
        ),
    ]
