# Generated by Django 3.0.4 on 2024-04-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_paperrecord_genre_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperchat',
            name='comment',
            field=models.TextField(max_length=500),
        ),
    ]
