# Generated by Django 3.0.4 on 2024-05-17 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_auto_20240410_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paperchat',
            old_name='paperrecord',
            new_name='record',
        ),
    ]
