# Generated by Django 3.0.4 on 2024-02-23 16:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('first_author', models.TextField(max_length=100)),
                ('pub_year', models.IntegerField(default=0)),
                ('genre', models.TextField(max_length=100)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('summary', models.TextField(max_length=500)),
                ('report', models.TextField(max_length=5000)),
                ('good_count', models.IntegerField(default=0)),
                ('chat_count', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('edit_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_owner', to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookrecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.BookRecord')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_owner', to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_owner', to='accounts.Account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=140)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('bookrecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.BookRecord')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_owner', to='accounts.Account')),
            ],
            options={
                'ordering': ('pub_date',),
            },
        ),
        migrations.AddField(
            model_name='bookrecord',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Group'),
        ),
        migrations.AddField(
            model_name='bookrecord',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_owner', to='accounts.Account'),
        ),
    ]
