# Generated by Django 3.0.4 on 2024-02-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='reply_id',
            field=models.IntegerField(default=-1),
        ),
    ]
