# Generated by Django 3.0.4 on 2024-02-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_chat_reply_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='reply_count',
            field=models.IntegerField(default=0),
        ),
    ]
