# Generated by Django 3.0.4 on 2024-03-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20240302_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrecord',
            name='img_path',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
