# Generated by Django 3.0.4 on 2024-06-09 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20240518_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='invitation_code',
            field=models.CharField(default='l7DLuEgV6Edodfs7', max_length=100, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
