# Generated by Django 3.0.4 on 2024-03-17 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20240311_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='LINE_ID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='LINE_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='secret_key',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
