# Generated by Django 3.0.4 on 2024-04-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20240318_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='icon_image',
            field=models.ImageField(blank=True, default='dafault.jpg', upload_to='profile_pics'),
        ),
    ]
