# Generated by Django 3.0.4 on 2024-04-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20240401_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='icon_image',
            field=models.ImageField(blank=True, default='profile_pics/dafault.jpg', upload_to='profile_pics'),
        ),
    ]
