# Generated by Django 3.0.4 on 2024-04-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20240401_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='icon_image',
            field=models.ImageField(blank=True, default='/media/profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
