# Generated by Django 3.0.4 on 2024-04-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20240401_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='LINE_ID',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
