# Generated by Django 3.0.4 on 2024-03-28 03:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0006_auto_20240302_0053'),
        ('accounts', '0006_auto_20240318_0336'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('director', models.TextField(blank=True, max_length=100, null=True)),
                ('img_path', models.TextField(blank=True, max_length=100, null=True)),
                ('pub_year', models.TextField(blank=True, default=0, null=True)),
                ('genre', models.TextField(blank=True, max_length=100, null=True)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('summary', models.TextField(blank=True, max_length=500, null=True)),
                ('report', models.TextField(max_length=5000)),
                ('good_count', models.IntegerField(default=0)),
                ('chat_count', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('edit_count', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_owner', to='accounts.Account')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='MovieChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=140)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('reply_id', models.IntegerField(default=-1)),
                ('reply_count', models.IntegerField(default=0)),
                ('movierecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.MovieRecord')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moviechat_owner', to='accounts.Account')),
            ],
            options={
                'ordering': ('pub_date',),
            },
        ),
    ]
