# Generated by Django 3.0.4 on 2024-04-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20240330_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviechat',
            name='comment',
            field=models.TextField(max_length=500),
        ),
    ]
